services:
  web:
    restart: unless-stopped
    # domainname: mydomain.com # if you want to use your own domain
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - target: 3000
        mode: ingress
        published: 3000
    deploy:
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M
    environment:
      - AUTH0_ISSUER_BASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_SECRET
      - AUTH0_BASE_URL
